### ISSUE TITLE
Fork para soporte de facturas "C" 

### ISSUE THREAD

**Issue by emafriedrich** [ombulabs/afip_bill#3]
Hola. 
Hice un fork para agregar soporte a facturas C https://github.com/emafriedrich/afip_bill

No se me ocurrió nada mejor que copiar la imagen de la factura b y su html para no tocar demasiado el código base, y no hacer malabares para mostrar la letra "C" en vez de la "B".

Como bravo no tiene soporte para emisión de facturas C también tuve que forkearlo.

https://github.com/emafriedrich/bravo

Así que como afip_bill va de la mano con bravo, me parece bien comentarlo.

**Comment by lubc** [comment]
Hola @emafriedrich , genial, gracias por compartir. Podrías crear un PR así lo revisamos. El soporte para factura C era algo pendiente así que viene bien.

**Comment by etagwerker** [comment]
@emafriedrich Buenas, pudiste ver esto? Si mandás un PR lo podemos revisar y sumar al proyecto. Gracias!

**Comment by emafriedrich** [comment]
@etagwerker buenas. Si, pero no me dí el tiempo de hacerlo, lo hago en estos días.

**Comment by bronzdoc** [comment]
closed by https://github.com/fastruby/afip_bill/pull/18
