### ISSUE TITLE
Facturas duplicadas (req. de la AFIP)

### ISSUE THREAD

**Issue by emafriedrich** [ombulabs/afip_bill#4]
Se me presentó la necesidad de hacer el duplicado de la factura, es requisito de la AFIP según entiendo. Lo solucioné a medias, como no soy bueno con ERB directo y por los tiempos que tenía, agregando una option a la generación de la factura, para mostrar "DUPLICADO" en lugar de original. Pero esto hace que el user deba imprimir el duplicado aparte, un horror. Creo el issue si alguien lo hace antes, sino luego con tiempo trato de hacerlo en un solo pdf.

**Comment by etagwerker** [comment]
@emafriedrich Creo que @mauro-oto lo resolvió con https://github.com/ombulabs/afip_bill/pull/8. Qué te parece esa solución?

**Comment by emafriedrich** [comment]
Genial. Como decia Mauro, estaria bueno pasarlo a un solo pdf mas adelante. Gracias @mauro-oto

**Comment by lubc** [comment]
Para poder tenerlo en un solo PDF primero habría que resolver #5 . Trataré de darle prioridad a ese issue. De momento la solución de @mauro-oto me parece bien

**Comment by ceneon** [comment]
Paso a comentar que estamos probando la gema, y esta solución nos es suficiente por ahora. Simplemente tenemos un botón de "imprimir original" y otro de "imprimir duplicado".

**Comment by bronzdoc** [comment]
Closed by https://github.com/fastruby/afip_bill/pull/8
